position_trajectory_controller_joint1:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - wheel_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

position_trajectory_controller_joint2:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - wheel_left_joint
    command_interfaces:
      - position
    state_interfaces:
      - position